### ISSUE TITLE
Ubuntu 18.04: kubernetes/scripts/master.sh hangs on Waiting for API server to respond

### ISSUE THREAD

**Issue by izelnakri** [hobby-kube/provisioning#15]
I was able to set up my kubernetes cluster on Vultr, I might create an example repo soon for it. Without this repository, this would not have been possible I think, so thanks a lot!

The issue I have is the master.sh seems to be blocking the if check and always resolves true:

```sh
until $(curl --output /dev/null --silent --head --fail http://localhost:6443); do
  echo "Waiting for API server to respond"
  sleep 5
done

// following never gets applied

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

# See: https://kubernetes.io/docs/admin/authorization/rbac/
kubectl create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts
```

All my nodes join the network when I run the full provision script but nodes stay with NotReady status due to the fact that the last two commands dont get executed on master. 

When I do ssh on master and run the last 2 commands nodes become "Ready" thus kubernetes setup completes however the terraform master.sh process keeps hanging on "Waiting for API server to respond".

**Comment by pstadler** [comment]
I'm not sure why this is happening. Please provide more details.

**Comment by openscript** [comment]
I ran into the same problem. What details could you help to investigate the problem?

**Comment by thorerik** [comment]
I changed the test from using curl to nc instead like the slave test:
```
until $(nc -z localhost 6443); do
  echo "Waiting for API server to respond"
  sleep 5
done
```
That made the deployment work for me

**Comment by openscript** [comment]
@thorerik Thank you! I'll verify tomorrow.

Are you using the Ubuntu 18.04 LTS image?

**Comment by pstadler** [comment]
Thank you, I will change this.

**Comment by pstadler** [comment]
@thorerik Did you need to change anything else to use Ubuntu 18.04 instead of 16.04 (besides changing the image variable of course)?

**Comment by thorerik** [comment]
Not yet, I got nginx ingress up and running with le, acording to your guide and manifests

**Comment by openscript** [comment]
It works for me now, too. Thank you :)
