### ISSUE TITLE
Failed to apply plan - missing certs

### ISSUE THREAD

**Issue by j3ddesign** [hobby-kube/provisioning#19]
I'm fairly new to Terraform so could be missing something obvious, however when trying to provision a cluster - I get the following error after a while

```
module.kubernetes.null_resource.kubectl: Provisioning with 'local-exec'...
module.kubernetes.null_resource.kubectl (local-exec): Executing: ["/bin/sh" "-c" "[ -d $HOME/.kube/<MyDomain> ] || mkdir -p $HOME/.kube/<MyDomain>"]
module.kubernetes.null_resource.kubectl: Provisioning with 'local-exec'...
module.kubernetes.null_resource.kubectl (local-exec): Executing: ["/bin/sh" "-c" "      scp -oStrictHostKeyChecking=no \\\n        root@<MyServerIP>:/etc/kubernetes/pki/{apiserver-kubelet-client.key,apiserver-kubelet-client.crt,ca.crt} \\\n        $HOME/.kube/<MyDomain>\n"]
module.kubernetes.null_resource.kubectl (local-exec): Warning: Permanently added '<MyServerIP>' (ECDSA) to the list of known hosts.
module.kubernetes.null_resource.kubectl (local-exec): scp: /etc/kubernetes/pki/apiserver-kubelet-client.key: No such file or directory
module.kubernetes.null_resource.kubectl (local-exec): scp: /etc/kubernetes/pki/apiserver-kubelet-client.crt: No such file or directory
module.kubernetes.null_resource.kubectl (local-exec): scp: /etc/kubernetes/pki/ca.crt: No such file or directory
```

**Comment by Qambar** [comment]
can you provide full log ?

**Comment by j3ddesign** [comment]
Sure can - my terminal didn't have the full log however this is a "very" large portion of it :) 

https://paste.ee/p/QDZ60

**Comment by j3ddesign** [comment]
I did some more digging and it seems that the master is supposed to have created certs (though I can't see where it would do this, I'm definitely missing something) which are then copied to local_exec, however these certs on master are either not created, or in a different dir perhaps?

Any help would be appreciated, I'm at a loss.
Thank you

**Comment by j3ddesign** [comment]
I decided to try another provider (I was using Linode via their provider plugin) and switched to DigitalOcean - this issue didn't arise there, though I'm not quite sure why it would be any different, as beyond the provider they are both running ubuntu 16.04.

Any idea why this would be the case?

**Comment by pstadler** [comment]
The problem is this:

```
[0m[0mmodule.kubernetes.null_resource.kubernetes[3] (remote-exec): modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.14.17-x86_64-linode99/modules.dep.bin'

[0m[0mmodule.kubernetes.null_resource.kubernetes[3] (remote-exec): modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/4.14.17-x86_64-linode99
```

You have to make sure to enable the required module(s) for your Kernel.

**Comment by pstadler** [comment]
Another error:

```
[0m[0mmodule.firewall.null_resource.firewall[0] (remote-exec): ERROR: Bad interface name: can't use interface aliases
```

Make sure to use a correct network interface. As far as I know, ufw will not work with interface aliases such as `eth0:0`.

**Comment by j3ddesign** [comment]
Ahhh ok - That gives me something to dig into, thank you!  👍
