### ISSUE TITLE
Scaling the cluster

### ISSUE THREAD

**Issue by davidcodesido** [hobby-kube/provisioning#29]
Is there a way to scale up the cluster with this terraform config?

For what I've seen, if you increase the count of the servers the IPs of the VPN may change. Furthermore, in the /etc/hosts it just piles up again all the hostnames with the new IPs. To overcome this I added a command to the remote-exec.

**Comment by pstadler** [comment]
Unfortunately, rescaling is not really supported (and will maybe never be). I'd suggest to deploy a new cluster instead.
