### ISSUE TITLE
Ubuntu 18.04: Wireguard errors on Hetzner Cloud

### ISSUE THREAD

**Issue by openscript** [hobby-kube/provisioning#41]
Unfortunately the deployment fails on Hetzner Cloud with the 18.04 image. I don't have much experience with Terraform. How can I investigate the problem?

Here is the error:
```
Error: Error applying plan:

2 error(s) occurred:

* module.wireguard.null_resource.wireguard[0]: error executing "/tmp/terraform_902354276.sh": Process exited with status 100
* module.wireguard.null_resource.wireguard[1]: error executing "/tmp/terraform_799075945.sh": Process exited with status 100

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

This is my variables.tf:

```
variable "hcloud_location" {
  default = "nbg1"
}

variable "hcloud_type" {
  default = "cx11"
}

variable "hcloud_image" {
  default = "ubuntu-18.04"
}
```

Thank you in advance. 🙂

**Comment by pstadler** [comment]
Well, I'm not exactly sure whether this is a problem with Wireguard or simply another case of Terraform's broken dependency resolution. Could you please provide further logs?

**Comment by pstadler** [comment]
@vhyza I'm not really fond of using grep to check whether apt is running, but I found the following solution which seems to combine the checks I tried out so far: https://askubuntu.com/a/373478/246100

**Comment by pstadler** [comment]
Fix: https://github.com/hobby-kube/provisioning/commit/a53f58d838331c247377314a69fc3148b6d059db

If you're still experiencing problems after this fix, don't hesitate to reopen this issue.

**Comment by pstadler** [comment]
I just realized that this issue is not really related to the fix. Sorry for the confusion.

**Comment by vhyza** [comment]
@pstadler thank you! Me neither. I'll try to replace the `grep` solution with your `fuser` if it solves the problem in my case...
