### ISSUE TITLE
your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1alpha3".

### ISSUE THREAD

**Issue by Qambar** [hobby-kube/provisioning#44]
I am getting the following error when i provision 

```
@your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1alpha3". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
```

after that it keeps on waiting for api to respond

```
module.kubernetes.null_resource.kubernetes[2] (remote-exec): Waiting for API server to respond
module.kubernetes.null_resource.kubernetes[1] (remote-exec): Waiting for API server to respond
module.kubernetes.null_resource.kubernetes.0: Still creating... (1m10s elapsed)
module.kubernetes.null_resource.kubernetes.1: Still creating... (1m10s elapsed)
module.kubernetes.null_resource.kubernetes.2: Still creating... (1m10s elapsed)
module.kubernetes.null_resource.kubernetes[2] (remote-exec): Waiting for API server
```

**Comment by korentsov-e** [comment]
Quick fix:
service/kubernetes/scripts/master.sh

-kubeadm init --config /tmp/master-configuration.yml \
+kubeadm config migrate --old-config /tmp/master-configuration.yml --new-config /tmp/new-master-configuration.yml

+kubeadm init --config /tmp/new-master-configuration.yml \
   --ignore-preflight-errors=Swap,NumCPU

**Comment by pstadler** [comment]
This has been fixed. See: https://github.com/hobby-kube/provisioning/commit/bfbf8009c184d1b103ee1bf94b89ea8d0c364fd0

**Comment by Qambar** [comment]
Thanks @pstadler
