### ISSUE TITLE
high cpu usage of weave

### ISSUE THREAD

**Issue by blinkeye** [hobby-kube/provisioning#53]
I can't explain why, but following a simple hcloud 4 server setup weave is acting out. Whenever I run a custom kafka producer which puts twitter json data into a kafka cluster weave eats more CPU than kafka producer itself.

![image](https://user-images.githubusercontent.com/1611556/66271975-48f68580-e864-11e9-927b-bf9501823b34.png)

It's reproducible on all 3 worker nodes. I also upgraded a node to have more CPU power but the behavour is the same:
![image](https://user-images.githubusercontent.com/1611556/66272002-8a873080-e864-11e9-872c-47683a3b9f34.png)

Any ideas? I don't observer this behaviour with my own PROD Hetzner K8s cluster with a similar (but manual) setup.

**Comment by pstadler** [comment]
What are the differences between your productive cluster and your Hobby Kube installation? Are you using WireGuard on your other cluster as well? Hetzner Cloud now offers private networking, maybe you could disable WireGuard and check whether the CPU impact is caused by it. I'm really curious.
