### ISSUE TITLE
Node reboots cause weave-net failure with --cluster-cidr

### ISSUE THREAD

**Issue by jawabuu** [hobby-kube/provisioning#71]
@pstadler 
When a node is rebooted, weave-net will not come up causing pods to remain hanging in 'Unknown' state.
To reproduce:
1. Deploy hobby-kube in digitalocean
2. Reboot any node
3. Once node is up
`kubectl get po -A`
```
NAMESPACE              NAME                                       READY   STATUS             RESTARTS   AGE
cert-manager           cert-manager-844dc75669-6mrlh              0/1     Unknown            0          37m
cert-manager           cert-manager-cainjector-7b744d56fb-tvpkf   0/1     Unknown            1          37m
cert-manager           cert-manager-webhook-7d6d4c78bc-pt2qv      0/1     Unknown            0          37m
default                net-58fcc844c4-nwnqr                       0/1     Unknown            0          38m
kube-system            traefik-xvffq                              0/1     Unknown            0          36m
kube-system            weave-net-hrrrd                            1/2     CrashLoopBackOff   1          13s

```
4. Check weave-net logs
`kubectl -n kube-system logs -f weave-net-hrrrd -c weave`
```
Network 10.96.0.0/16 overlaps with existing route 10.96.0.0/16 on host
```
5. SSH into node and run `ip route`, observe this route
```
10.96.0.0/16 dev wg0 scope link src 10.0.1.1
```
which is created by `overlay-route.service`
conflicts with the one weave wants to create.

Weave is deployed as per docs recommendation
https://github.com/hobby-kube/provisioning/blob/1168754213d360fd289c627a494015dff24ac692/service/kubernetes/scripts/master.sh#L17

```
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.IPALLOC_RANGE=var.overlay_cidr"
```

**Comment by jawabuu** [comment]
@pstadler I'm wondering if this is necessary at all

https://github.com/hobby-kube/provisioning/blob/1168754213d360fd289c627a494015dff24ac692/security/wireguard/templates/overlay-route.service#L8

considering ufw blocks communication on the private network apart from the globals and wireguard port.

https://github.com/hobby-kube/provisioning/blob/1168754213d360fd289c627a494015dff24ac692/security/ufw/scripts/ufw.sh#L6-L8

Also the nodes register to cluster using the vpn ip of the master so all inter node traffic already goes through wireguard.
Let me know what I'm overlooking.

**Comment by jawabuu** [comment]
A comment [here](
https://github.com/weaveworks/weave/issues/3588#issuecomment-458068366) explains the [mechanism](
https://github.com/weaveworks/weave/blob/34de0b10a69c2fa11f2314bfe0e449f739a96cd8/prog/kube-utils/main.go#L36-L73)
through which weave decides which interface to use.
In short, specifying the `--node-ip` label equal to the vpn_ip is enough to ensure weave communicates through the wireguard interface.
```
"KUBELET_EXTRA_ARGS=--fail-swap-on=false --node-ip=var.vpn_ip"
```

**Comment by pstadler** [comment]
Hey @jawabuu

Thanks for reporting and looking into it! I'm not sure whether something changed in weave that makes manually setting up the route break things. I'm preparing a fix - would you be willing to test it?

**Comment by jawabuu** [comment]
@pstadler Yes I would.
To be fair this would only affect cases where one restarts nodes and ip ranges conflict.
Otherwise one would be unaware of it

**Comment by jawabuu** [comment]
I think this should also be disabled
`ExecStart=/sbin/ip route add ${overlay_cidr} dev wg0 src ${address}`
now that you are using `--node-ip`

**Comment by pstadler** [comment]
Okay I tested a couple of things. To cut a long story short, you can't use overlay_cidr for weave, pods will error.
This is how a healthy route table looks like:

```
default via 172.31.1.1 dev eth0 proto dhcp src 116.203.25.52 metric 100
10.0.1.1 dev wg0 scope link
10.0.1.2 dev wg0 scope link
10.32.0.0/12 dev weave proto kernel scope link src 10.32.0.1 # <-- weave
10.96.0.0/16 dev wg0 scope link src 10.0.1.3 # <-- k8s via wg0
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.31.1.1 dev eth0 proto dhcp scope link src 116.203.25.52 metric 100
```

I'm by no means an expert in networking but I'm pretty sure your setup already fails before a restart.

**Comment by jawabuu** [comment]
Thanks @pstadler 
You are correct, it shouldn't start.(It does though but for a different reason)
A more pertinent question is, why is this necessary?
```
10.96.0.0/16 dev wg0 scope link src 10.0.1.3 # <-- k8s via wg0
```
considering it is not used at all as weave uses
```
10.32.0.0/12 dev weave proto kernel scope link src 10.32.0.1 # <-- weave
```
If you check your pods, do any report addresses from
`10.96.x.x`?

**Comment by jawabuu** [comment]
I believe the `overlay_cidr` is ignored entirely in the current setup because weave uses a different cidr.
If I am correct the route serves no purpose.

**Comment by pstadler** [comment]
I think there's a pod network cidr (weave) and a service network cidr (k8s) that are running independently, but I honestly don't have the time to dive into it. If you feel like digging a little deeper, please let me know if you figure out something interesting.

**Comment by jawabuu** [comment]
@pstadler Thanks. I'll dig into it further.
